// Bible Quest question bank — 17 story-based levels in narrative order.
// Each level is a themed round; questions are ordered easy -> hard so difficulty
// ramps within the round. Choices are shuffled at runtime (game.js), so the
// order here doesn't matter — `a` is always the correct answer, `d` the three
// distractors.
//
// Every question is drawn from a well-known Bible story and double-checked for
// factual accuracy (book references noted per level). Kept kid-appropriate for
// ages 6-12: no violence/gore, no theologically contentious content — stories,
// people, places, numbers and simple facts.
//
// This file is a plain browser script (top-level `const LEVELS`) so it can also
// be loaded into the Node test harness (tests/questions.test.js) as a data
// linter. Keep it export-free.

const LEVELS = [
  {
    title: "Creation & the Garden",
    emoji: "🌱",
    ref: "Genesis 1–3",
    theme: ["#4caf7d", "#2e8b57"],
    questions: [
      { q: "Fill in the blank: \"In the beginning God created the heavens and the ___.\"", a: "Earth", d: ["Angels", "Sea", "Light"] },
      { q: "What did God create on the very first day?", a: "Light", d: ["Animals", "The sea", "The stars"] },
      { q: "Who was the first man God made?", a: "Adam", d: ["Noah", "Moses", "Abraham"] },
      { q: "Who was the first woman God made?", a: "Eve", d: ["Sarah", "Mary", "Ruth"] },
      { q: "What was the name of the garden where Adam and Eve lived?", a: "Eden", d: ["Canaan", "Babylon", "Nazareth"] },
      { q: "How many days did God take to make the world, before he rested?", a: "Six", d: ["Three", "Seven", "Twelve"] },
      { q: "What did God do on the seventh day?", a: "He rested", d: ["Made the sun", "Made the fish", "Made the rain"] },
      { q: "Which animal tempted Eve to eat the forbidden fruit?", a: "A serpent", d: ["A lion", "A goat", "A dove"] },
      { q: "God made Eve from one of Adam's ___.", a: "Ribs", d: ["Hands", "Feet", "Fingers"] },
      { q: "Which tree were Adam and Eve told not to eat from?", a: "The tree of the knowledge of good and evil", d: ["The olive tree", "The fig tree", "The tree of life"] },
    ],
  },
  {
    title: "Noah's Ark",
    emoji: "🌈",
    ref: "Genesis 6–9",
    theme: ["#3aa0d9", "#2472b0"],
    questions: [
      { q: "Who did God ask to build a big boat called the ark?", a: "Noah", d: ["Abraham", "Moses", "Adam"] },
      { q: "What did God send to flood the whole earth?", a: "Rain", d: ["Fire", "Wind", "Snow"] },
      { q: "How many days and nights did the rain fall?", a: "Forty", d: ["Seven", "Twelve", "One hundred"] },
      { q: "Noah brought the animals onto the ark in groups of how many?", a: "Two", d: ["Three", "Five", "Ten"] },
      { q: "What was the ark made of?", a: "Wood", d: ["Stone", "Gold", "Reeds"] },
      { q: "Which bird did Noah send out first, that did not come back?", a: "A raven", d: ["A dove", "An eagle", "An owl"] },
      { q: "Which bird returned to Noah carrying an olive leaf?", a: "A dove", d: ["A raven", "A sparrow", "A robin"] },
      { q: "On which mountain did the ark finally come to rest?", a: "Ararat", d: ["Sinai", "Zion", "Carmel"] },
      { q: "How many people were kept safe on the ark?", a: "Eight", d: ["Two", "Four", "Twelve"] },
      { q: "What sign did God put in the sky as a promise never to flood the whole earth again?", a: "A rainbow", d: ["A bright star", "A cloud", "The moon"] },
    ],
  },
  {
    title: "Abraham, Isaac & Jacob",
    emoji: "⭐",
    ref: "Genesis 12–35",
    theme: ["#e0a53c", "#c07a1e"],
    questions: [
      { q: "God told Abraham his family would be as many as the ___ in the sky.", a: "Stars", d: ["Birds", "Clouds", "Raindrops"] },
      { q: "What was the name of Abraham's wife?", a: "Sarah", d: ["Rachel", "Rebekah", "Leah"] },
      { q: "What son did God promise to Abraham and Sarah in their old age?", a: "Isaac", d: ["Jacob", "Joseph", "Esau"] },
      { q: "What was Abraham called before God changed his name?", a: "Abram", d: ["Adam", "Aaron", "Amos"] },
      { q: "Who did Isaac marry?", a: "Rebekah", d: ["Sarah", "Rachel", "Leah"] },
      { q: "Isaac had twin sons. Which older son sold his birthright?", a: "Esau", d: ["Jacob", "Levi", "Judah"] },
      { q: "What did Esau trade his birthright for?", a: "A bowl of stew", d: ["A new coat", "A flock of sheep", "A bag of gold"] },
      { q: "In a dream, Jacob saw a ladder to heaven. What were the angels doing on it?", a: "Going up and down", d: ["Singing", "Sleeping", "Sitting still"] },
      { q: "God gave Jacob a new name. What was it?", a: "Israel", d: ["Isaac", "Abraham", "Ishmael"] },
      { q: "How many sons did Jacob have, who became the tribes of Israel?", a: "Twelve", d: ["Seven", "Ten", "Two"] },
    ],
  },
  {
    title: "Joseph",
    emoji: "🧥",
    ref: "Genesis 37–50",
    theme: ["#d94f8c", "#a83268"],
    questions: [
      { q: "Joseph's father gave him a special coat. What was it like?", a: "Colourful", d: ["Plain white", "Made of fur", "All black"] },
      { q: "Who was Joseph's father?", a: "Jacob", d: ["Isaac", "Abraham", "Esau"] },
      { q: "How did Joseph's older brothers feel about him?", a: "Jealous", d: ["Proud", "Scared", "Bored"] },
      { q: "What did Joseph's brothers do to him?", a: "Sold him as a slave", d: ["Made him a king", "Sent him to school", "Gave him gold"] },
      { q: "In which country did Joseph become a powerful leader?", a: "Egypt", d: ["Israel", "Babylon", "Persia"] },
      { q: "God gave Joseph the ability to explain the meaning of what?", a: "Dreams", d: ["Songs", "Maps", "Riddles"] },
      { q: "Pharaoh dreamed of seven fat cows and seven ___ cows.", a: "Thin", d: ["Purple", "Flying", "Sleeping"] },
      { q: "Joseph told Egypt to store up food to get ready for what?", a: "A famine", d: ["A war", "A flood", "A festival"] },
      { q: "What was the name of Joseph's youngest brother?", a: "Benjamin", d: ["Reuben", "Judah", "Levi"] },
      { q: "When his brothers came to Egypt for food, what did Joseph do?", a: "Forgave them", d: ["Locked them away", "Sent them home hungry", "Pretended not to know them forever"] },
    ],
  },
  {
    title: "Moses & the Exodus",
    emoji: "🔥",
    ref: "Exodus 1–15",
    theme: ["#e2603c", "#b23c1f"],
    questions: [
      { q: "As a baby, Moses was hidden in a basket on which river?", a: "The Nile", d: ["The Jordan", "The Red Sea", "The Euphrates"] },
      { q: "Who found baby Moses floating in the basket?", a: "Pharaoh's daughter", d: ["His own sister", "A shepherd", "A fisherman"] },
      { q: "God spoke to Moses from a bush that was doing what?", a: "Burning without burning up", d: ["Growing fruit", "Talking loudly", "Blooming flowers"] },
      { q: "What did God tell Moses to say to Pharaoh?", a: "\"Let my people go\"", d: ["\"Build me a temple\"", "\"Bring me gold\"", "\"Make me king\""] },
      { q: "Who was Moses' brother who helped him speak to Pharaoh?", a: "Aaron", d: ["Caleb", "Joshua", "Nathan"] },
      { q: "How many plagues did God send on Egypt?", a: "Ten", d: ["Three", "Seven", "Twelve"] },
      { q: "Which of these was one of the plagues on Egypt?", a: "Frogs", d: ["Spiders", "Snowstorms", "Earthquakes"] },
      { q: "On the night of the very last plague, what did the Israelites paint on their doors?", a: "Lamb's blood", d: ["Gold paint", "Their names", "A star"] },
      { q: "Which sea did God part so the Israelites could cross on dry land?", a: "The Red Sea", d: ["The Dead Sea", "The Sea of Galilee", "The Nile"] },
      { q: "That special night God passed over the Israelites' homes. What is this event called?", a: "The Passover", d: ["The Sabbath", "The Harvest", "The Jubilee"] },
    ],
  },
  {
    title: "Wilderness & the Ten Commandments",
    emoji: "📜",
    ref: "Exodus 16–20; Numbers",
    theme: ["#c9a227", "#997a12"],
    questions: [
      { q: "What food did God send from heaven each morning in the desert?", a: "Manna", d: ["Bread rolls", "Fresh fish", "Grapes"] },
      { q: "When the people were thirsty, God brought water out of a ___.", a: "Rock", d: ["Tree", "Cloud", "Deep well"] },
      { q: "On which mountain did Moses receive the Ten Commandments?", a: "Mount Sinai", d: ["Mount Zion", "Mount Carmel", "Mount of Olives"] },
      { q: "How many commandments did God give to Moses?", a: "Ten", d: ["Five", "Seven", "Twelve"] },
      { q: "The commandments were written on tablets made of what?", a: "Stone", d: ["Wood", "Gold", "Clay"] },
      { q: "Which of these is one of the Ten Commandments?", a: "Do not steal", d: ["Do not swim", "Do not travel", "Do not sing"] },
      { q: "\"Honour your father and your ___\" is one of the commandments.", a: "Mother", d: ["Country", "King", "Teacher"] },
      { q: "What led the Israelites through the desert during the day?", a: "A pillar of cloud", d: ["A bright star", "A flying bird", "A paper map"] },
      { q: "While Moses was on the mountain, the people made an idol shaped like a golden ___.", a: "Calf", d: ["Snake", "Bird", "Lion"] },
      { q: "How many years did the Israelites wander in the wilderness?", a: "Forty", d: ["Ten", "Four", "One hundred"] },
    ],
  },
  {
    title: "Joshua & the Promised Land",
    emoji: "🎺",
    ref: "Joshua",
    theme: ["#c14a3e", "#93332a"],
    questions: [
      { q: "Who became the leader of Israel after Moses died?", a: "Joshua", d: ["Aaron", "Caleb", "David"] },
      { q: "Which river did the Israelites cross to enter the Promised Land?", a: "The Jordan", d: ["The Nile", "The Red Sea", "The Euphrates"] },
      { q: "The Promised Land was described as flowing with milk and ___.", a: "Honey", d: ["Water", "Gold", "Oil"] },
      { q: "What was the name of the city with the walls that fell down?", a: "Jericho", d: ["Jerusalem", "Babylon", "Nazareth"] },
      { q: "For how many days did the Israelites march around Jericho?", a: "Seven", d: ["Three", "Ten", "Forty"] },
      { q: "What did the priests blow as they marched around the city?", a: "Trumpets", d: ["Whistles", "Drums", "Flutes"] },
      { q: "On the last day, what did the people do that made the walls fall?", a: "They shouted", d: ["They dug tunnels", "They threw stones", "They prayed silently"] },
      { q: "What happened to the walls of Jericho?", a: "They fell down flat", d: ["They caught fire", "They turned to water", "They grew taller"] },
      { q: "Which woman in Jericho helped hide the two Israelite spies?", a: "Rahab", d: ["Ruth", "Deborah", "Miriam"] },
      { q: "God told Joshua to be strong and ___.", a: "Courageous", d: ["Quiet", "Quick", "Rich"] },
    ],
  },
  {
    title: "Judges: Samson, Gideon & Deborah",
    emoji: "💪",
    ref: "Judges",
    theme: ["#7a54c9", "#553a94"],
    questions: [
      { q: "Which strong man got his amazing strength from his long hair?", a: "Samson", d: ["Gideon", "Saul", "Goliath"] },
      { q: "A \"judge\" in this part of the Bible was a kind of what?", a: "Leader", d: ["Priest", "King", "Farmer"] },
      { q: "Which judge was a wise woman who led Israel?", a: "Deborah", d: ["Miriam", "Esther", "Rahab"] },
      { q: "Where did Deborah sit to help settle the people's problems?", a: "Under a palm tree", d: ["In a deep cave", "On a mountain top", "Beside the sea"] },
      { q: "Samson was so strong he once fought a ___ with his bare hands.", a: "Lion", d: ["Bear", "Wolf", "Bull"] },
      { q: "Who cut Samson's hair, which took away his strength?", a: "Delilah", d: ["Deborah", "Ruth", "Miriam"] },
      { q: "Gideon asked God for a sign using a wool fleece and morning ___.", a: "Dew", d: ["Fire", "Rain", "Wind"] },
      { q: "God let Gideon keep only a small army. How many men?", a: "300", d: ["3,000", "100", "30"] },
      { q: "Gideon's soldiers hid burning torches inside ___ to surprise the enemy.", a: "Clay jars", d: ["Baskets", "Blankets", "Wooden boxes"] },
      { q: "Samson's enemies, whom he defeated at the end, were the ___.", a: "Philistines", d: ["Egyptians", "Romans", "Babylonians"] },
    ],
  },
  {
    title: "David & Goliath / King David",
    emoji: "🎯",
    ref: "1 & 2 Samuel",
    theme: ["#3f8f4f", "#2c6a39"],
    questions: [
      { q: "Before he was king, what was David's job?", a: "A shepherd", d: ["A fisherman", "A carpenter", "A soldier"] },
      { q: "What giant did the young David defeat?", a: "Goliath", d: ["King Saul", "Samson", "Og"] },
      { q: "Which army did Goliath fight for?", a: "The Philistines", d: ["The Egyptians", "The Romans", "The Babylonians"] },
      { q: "What weapon did David use to defeat Goliath?", a: "A sling and a stone", d: ["A sharp sword", "A bow and arrow", "A long spear"] },
      { q: "How many smooth stones did David pick from the stream?", a: "Five", d: ["One", "Three", "Ten"] },
      { q: "What instrument did David play to comfort King Saul?", a: "A harp", d: ["A drum", "A flute", "A trumpet"] },
      { q: "Who was the king before David who became jealous of him?", a: "Saul", d: ["Solomon", "Samuel", "Absalom"] },
      { q: "Who was David's loyal best friend, the king's son?", a: "Jonathan", d: ["Nathan", "Samuel", "Joab"] },
      { q: "Which prophet anointed David to become king?", a: "Samuel", d: ["Elijah", "Nathan", "Moses"] },
      { q: "David wrote many songs and prayers found in which book of the Bible?", a: "Psalms", d: ["Proverbs", "Genesis", "Kings"] },
    ],
  },
  {
    title: "Solomon",
    emoji: "👑",
    ref: "1 Kings 1–11",
    theme: ["#d4a017", "#a67c00"],
    questions: [
      { q: "Who was Solomon's father?", a: "David", d: ["Saul", "Samuel", "Abraham"] },
      { q: "When God offered Solomon anything he wanted, what did Solomon ask for?", a: "Wisdom", d: ["Gold", "A long life", "Power over kings"] },
      { q: "Solomon became famous around the world for being very ___.", a: "Wise", d: ["Tall", "Fast", "Young"] },
      { q: "Two mothers argued over one baby. The real mother showed her love by being willing to ___.", a: "Give the baby to the other woman", d: ["Fight for the baby", "Take gold instead", "Walk away angry"] },
      { q: "What special building did Solomon build for God in Jerusalem?", a: "The Temple", d: ["A palace", "A city wall", "A tall tower"] },
      { q: "Which faraway queen came to test Solomon's wisdom?", a: "The Queen of Sheba", d: ["Queen Esther", "Queen Jezebel", "The Queen of Egypt"] },
      { q: "The temple Solomon built was covered with lots of which precious metal?", a: "Gold", d: ["Tin", "Iron", "Bronze"] },
      { q: "Solomon wrote many wise sayings found in which book?", a: "Proverbs", d: ["Psalms", "Exodus", "Acts"] },
      { q: "Solomon was the king of which nation?", a: "Israel", d: ["Egypt", "Persia", "Rome"] },
      { q: "During Solomon's rule, the kingdom was known for its peace and great ___.", a: "Wealth", d: ["Wars", "Deserts", "Storms"] },
    ],
  },
  {
    title: "Elijah & Elisha",
    emoji: "🕊️",
    ref: "1 Kings 17 – 2 Kings 6",
    theme: ["#4a90c2", "#2f6690"],
    questions: [
      { q: "Elijah was a ___ who spoke God's messages to the people.", a: "Prophet", d: ["King", "Priest", "Soldier"] },
      { q: "During a drought, which birds brought food to Elijah?", a: "Ravens", d: ["Doves", "Eagles", "Sparrows"] },
      { q: "On Mount Carmel, fire came down from God and burned up the ___.", a: "Sacrifice on the altar", d: ["Whole city", "Nearby forest", "Mountain top"] },
      { q: "Elijah heard God not in the wind or earthquake, but in a gentle ___.", a: "Whisper", d: ["Song", "Shout", "Trumpet"] },
      { q: "How did Elijah go up to heaven?", a: "In a whirlwind with a chariot of fire", d: ["On a tall ladder", "In a golden boat", "On a white horse"] },
      { q: "Who became the next great prophet after Elijah?", a: "Elisha", d: ["Isaiah", "Samuel", "Nathan"] },
      { q: "Elisha helped a poor widow by filling many jars with ___.", a: "Oil", d: ["Water", "Wine", "Honey"] },
      { q: "Elisha told the soldier Naaman to wash in which river to be healed?", a: "The Jordan", d: ["The Nile", "The Red Sea", "The Euphrates"] },
      { q: "How many times did Naaman have to dip in the river to be healed?", a: "Seven", d: ["Three", "One", "Ten"] },
      { q: "Which evil queen was an enemy of Elijah?", a: "Jezebel", d: ["Delilah", "Ruth", "Esther"] },
    ],
  },
  {
    title: "Daniel & the Lions' Den",
    emoji: "🦁",
    ref: "Daniel",
    theme: ["#c77b30", "#96591c"],
    questions: [
      { q: "Daniel was taken far from home to live in which great kingdom?", a: "Babylon", d: ["Egypt", "Rome", "Greece"] },
      { q: "Daniel was known for explaining the king's ___.", a: "Dreams", d: ["Letters", "Maps", "Songs"] },
      { q: "Daniel's three friends refused to bow to a golden ___.", a: "Statue", d: ["Crown", "Chair", "Gate"] },
      { q: "Daniel's three friends were thrown into a fiery ___.", a: "Furnace", d: ["Pit", "River", "Cave"] },
      { q: "What happened to Daniel's friends inside the fire?", a: "They were not burned at all", d: ["They put it out with water", "They dug an escape tunnel", "They turned into smoke"] },
      { q: "What did Daniel do three times a day that got him in trouble?", a: "Prayed to God", d: ["Sang loud songs", "Ate special food", "Read old scrolls"] },
      { q: "Daniel was thrown into a den full of which animals?", a: "Lions", d: ["Bears", "Wolves", "Snakes"] },
      { q: "How did God protect Daniel in the den?", a: "He sent an angel to shut the lions' mouths", d: ["He made the lions fall asleep", "He turned the lions to stone", "He fed the lions first"] },
      { q: "What happened to Daniel in the lions' den?", a: "He was kept completely safe", d: ["He tamed them with music", "He quietly ran away", "He fought them off"] },
      { q: "Because Daniel trusted God, the king made a law telling everyone to respect ___.", a: "Daniel's God", d: ["Daniel himself", "The lions", "The golden statue"] },
    ],
  },
  {
    title: "Jonah",
    emoji: "🐋",
    ref: "Jonah",
    theme: ["#2f8f9d", "#1f6b76"],
    questions: [
      { q: "God told Jonah to go and preach to which city?", a: "Nineveh", d: ["Jerusalem", "Babylon", "Bethlehem"] },
      { q: "Instead of obeying, Jonah got on a boat going the opposite way. What happened at sea?", a: "A huge storm", d: ["The boat sank at once", "A rainbow appeared", "Nothing at all"] },
      { q: "To calm the storm, what did the sailors do with Jonah?", a: "Threw him into the sea", d: ["Locked him below deck", "Gave him a small boat", "Rowed him to shore"] },
      { q: "What swallowed Jonah in the sea?", a: "A great fish", d: ["A shark", "A crocodile", "A giant crab"] },
      { q: "How many days and nights was Jonah inside the fish?", a: "Three", d: ["One", "Seven", "Forty"] },
      { q: "What did Jonah do while he was inside the fish?", a: "Prayed to God", d: ["Fell asleep", "Cried for food", "Nothing at all"] },
      { q: "After the fish let him out, what did Jonah finally do?", a: "Went to Nineveh", d: ["Went back home", "Got on another boat", "Hid in a cave"] },
      { q: "When Jonah warned the people of Nineveh, how did they respond?", a: "They were sorry and turned to God", d: ["They laughed at him", "They chased him away", "They ignored him"] },
      { q: "God grew a plant to shade Jonah, but what happened to it?", a: "It withered away", d: ["It grew into a tree", "It turned to gold", "It floated away"] },
      { q: "What does the story of Jonah teach us about God?", a: "God is kind and forgiving", d: ["God likes big boats", "God lives far away", "God loves only one city"] },
    ],
  },
  {
    title: "Jesus' Birth",
    emoji: "⭐",
    ref: "Matthew 1–2; Luke 1–2",
    theme: ["#3d5af1", "#2b41c9"],
    questions: [
      { q: "Who was the mother of Jesus?", a: "Mary", d: ["Martha", "Elizabeth", "Ruth"] },
      { q: "Who was Mary's husband, Jesus' earthly father?", a: "Joseph", d: ["Zechariah", "Simeon", "John"] },
      { q: "Which angel told Mary she would have a very special baby?", a: "Gabriel", d: ["Michael", "Raphael", "Peter"] },
      { q: "In which town was Jesus born?", a: "Bethlehem", d: ["Nazareth", "Jerusalem", "Jericho"] },
      { q: "What name did the angel say to give the baby?", a: "Jesus", d: ["John", "James", "Isaac"] },
      { q: "Where was baby Jesus laid because there was no room in the inn?", a: "In a manger", d: ["In a soft bed", "In a basket", "In a palace"] },
      { q: "Who were the first people the angels told about Jesus' birth?", a: "Shepherds", d: ["Kings", "Fishermen", "Soldiers"] },
      { q: "What did the wise men follow to find the baby Jesus?", a: "A star", d: ["A paper map", "An angel", "A river"] },
      { q: "Which of these was a gift the wise men brought to Jesus?", a: "Gold", d: ["Silver", "A little lamb", "Fresh bread"] },
      { q: "Which jealous king tried to harm the baby Jesus?", a: "King Herod", d: ["King David", "King Saul", "Caesar"] },
    ],
  },
  {
    title: "Jesus' Miracles & Parables",
    emoji: "✨",
    ref: "The Gospels",
    theme: ["#e0a92e", "#b3831c"],
    questions: [
      { q: "At a wedding in Cana, Jesus turned water into what?", a: "Wine", d: ["Bread", "Oil", "Milk"] },
      { q: "Jesus fed a huge crowd with five loaves and two ___.", a: "Fish", d: ["Baskets", "Coins", "Cakes"] },
      { q: "About how many people did Jesus feed with the loaves and fish?", a: "Five thousand", d: ["Fifty", "Five hundred", "One million"] },
      { q: "Jesus amazed his friends by walking on top of the ___.", a: "Water", d: ["Clouds", "Mountains", "Rooftops"] },
      { q: "Jesus calmed a storm on the sea by saying, \"Peace, be ___.\"", a: "Still", d: ["Gone", "Quiet", "Away"] },
      { q: "In one parable, a shepherd left ninety-nine sheep to search for the ___ that was lost.", a: "One", d: ["Ten", "Fifty", "Hundred"] },
      { q: "In the story of the Good Samaritan, who stopped to help the hurt man?", a: "A Samaritan", d: ["A priest", "A king", "A soldier"] },
      { q: "Jesus brought his friend Lazarus back to life. Lazarus had been ___.", a: "Dead", d: ["Only asleep", "Just sick", "Simply lost"] },
      { q: "In the parable of the lost son, how did the father react when his son came home?", a: "He welcomed him with a party", d: ["He sent him away", "He stayed angry", "He ignored him"] },
      { q: "Jesus healed ten men of a skin disease, but how many came back to say thank you?", a: "One", d: ["Ten", "Five", "None"] },
    ],
  },
  {
    title: "Easter: Death & Resurrection",
    emoji: "✝️",
    ref: "The Gospels",
    theme: ["#8e44ad", "#652d7d"],
    questions: [
      { q: "Jesus rode into Jerusalem on which animal while people waved palm branches?", a: "A donkey", d: ["A horse", "A camel", "An elephant"] },
      { q: "How many disciples did Jesus choose to follow him closely?", a: "Twelve", d: ["Three", "Seven", "Ten"] },
      { q: "What special meal did Jesus share with his disciples the night before he died?", a: "The Last Supper", d: ["A big breakfast", "A wedding feast", "A picnic"] },
      { q: "Which disciple betrayed Jesus?", a: "Judas", d: ["Peter", "John", "Andrew"] },
      { q: "Which disciple said three times that he did not know Jesus?", a: "Peter", d: ["John", "Thomas", "Matthew"] },
      { q: "Jesus was put to death on a ___.", a: "Cross", d: ["Tall tower", "Stone wall", "Wooden bridge"] },
      { q: "After Jesus died, where was his body placed?", a: "In a tomb", d: ["In a house", "In a boat", "In the temple"] },
      { q: "What was rolled in front of the tomb?", a: "A large stone", d: ["A wooden door", "A heavy curtain", "An iron gate"] },
      { q: "On the third day, what wonderful thing happened?", a: "Jesus rose from the dead", d: ["The tomb vanished", "An angel became king", "Nothing happened"] },
      { q: "Who first discovered that Jesus' tomb was empty on Easter morning?", a: "Some women", d: ["The soldiers", "The wise men", "Pilate"] },
    ],
  },
  {
    title: "Paul's Journeys & the Early Church",
    emoji: "⛵",
    ref: "Acts",
    theme: ["#c0553b", "#933f2b"],
    questions: [
      { q: "Before he followed Jesus, Paul was known by which name?", a: "Saul", d: ["Simon", "Silas", "Stephen"] },
      { q: "On the road to Damascus, what happened to Saul?", a: "A bright light shone and Jesus spoke to him", d: ["He found buried treasure", "He met a great king", "He lost his way"] },
      { q: "Right after the bright light, what happened to Saul's eyes?", a: "He became blind for a while", d: ["They started to glow", "He could see far away", "Nothing changed"] },
      { q: "After meeting Jesus, Paul travelled far and wide to tell people about ___.", a: "Jesus", d: ["Himself", "Gold and riches", "His travels"] },
      { q: "Paul helped start many groups of believers called ___.", a: "Churches", d: ["Schools", "Armies", "Markets"] },
      { q: "Paul wrote many ___ to the churches, which became books in the Bible.", a: "Letters", d: ["Songs", "Maps", "Poems only"] },
      { q: "When an earthquake shook their prison, what were Paul and Silas doing?", a: "Singing and praying", d: ["Sleeping", "Digging a tunnel", "Shouting for help"] },
      { q: "On which day did the Holy Spirit come with what looked like tongues of fire?", a: "Pentecost", d: ["Passover", "Christmas", "The Sabbath"] },
      { q: "Who was the first follower of Jesus to die for his faith?", a: "Stephen", d: ["Paul", "Judas", "Thomas"] },
      { q: "The early church shared the good news of Jesus with ___.", a: "People everywhere", d: ["Only kings", "Only children", "Only soldiers"] },
    ],
  },
];
